name: Build Egg Drop App

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Build executable
        run: pyinstaller --onefile main.py

      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: EggDrop-${{ matrix.os }}
          path: dist/*

